tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk
  - name: terraform-cli
    before: |
      source bin/tf_cli_install.sh
  - name: aws-cli
    env: 
        AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source bin/aws_cli_install.sh



