#!/usr/bin/env bash

echo "Deleting all files in an S3 bucket"

# Check if the bucket name is passed as an argument
if [ -z "$1" ]; then
  echo "Bucket name is not provided or is empty"
  exit 1
fi

BUCKET_NAME="$1"

aws s3 rm "s3://$BUCKET_NAME" --recursive
