AWSTemplateFormatVersion: "2010-09-09"
Description: "A simple S3 Bucket"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
# We don't need to supply the name of the bucket, CloudFormation will generate a unique name for us
